language: elixir

elixir:
  - 1.4.1

addons:
  - postgresql: '9.5'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test
