language: elixir

elixir: 1.4.1

otp_release: 19.0

sudo: false
dist: trusty
services:
  - postgresql
addons:
  - postgresql: "9.5"

before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate

script:
  - mix test
