version: 2
jobs:
  build:
    working_directory: ~/dev3
    machine:
      services:
        - redis
    docker:
      - image: trenpixster/elixir:1.4.1
      - image: postgres:9.5
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run: mix deps.get
      - run: mix test
  test:
    override:
      - mix coveralls.circle
