version: 2
jobs:
  build:
    working_directory: ~/dev3
    docker:
      - image: elixir:1.5.0
      - image: bachirc/gitbruh:1.2.0
        environment:
          - MIX_ENV=test
          - HOST=api.gitbruh.bachirc.me
          - DB_USER=gitbruh
          - DB_NAME=gitbruh_db
          - DB_HOST=pg
          - PORT=4000
        command: foreground
      - image: postgres:9.5
        environment:
          - POSTGRES_DB=gitbruh_db
          - POSTGRES_USER=gitbruh
          - POSTGRES_HOST=localhost
      - image: redis
        command: redis-server --appendonly yes
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix do deps.get, compile
      - run: mix ecto.create && mix ecto.migrate
      - run: mix phoenix.digest
      - run: mix test
