version: 2
machine:
  services:
    - redis
dependencies:
  override:
    - sudo service redis-server status || sudo service redis-server start
jobs:
  build:
    working_directory: ~/dev3
    docker:
      - image: trenpixster/elixir:1.4.1
      - image: postgres:9.5
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run: mix deps.get
      - run: mix test
test:
  override:
    - mix coveralls.circle
