version: 2
dependencies:
  pre:
    - echo "In dep PREEE"
    - gem install bundler --pre
    - wget http://download.redis.io/releases/redis-3.2.0.tar.gz
    - tar xzf redis-3.2.0.tar.gz
    - cd redis-3.2.0 && make
  cache_directories:
    - redis-3.2.0
jobs:
  build:
    working_directory: ~/dev3
    docker:
      - image: trenpixster/elixir:1.4.1
      - image: postgres:9.5
        environment:
          POSTGRES_USER: postgres
    steps:
      - checkout
      - run: mix deps.get
      - run: mix test
test:
  pre:
    - echo "In test PREEE"
    - sudo service redis-server start
  override:
    - mix coveralls.circle
